### ISSUE TITLE
ReferenceError: router is not defined

### ISSUE THREAD

**Issue by ifour-vimal** [dhirajpatra/ckeditor_nodejs_with_img_upload#1]
I am getting below error after running your code as suggested by you.

Please see below error:
```
router.use(busboy());
^

ReferenceError: router is not defined
    at Object.<anonymous> (D:\home\Test\ckeditor_nodejs_with_img_upload\app.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
```

Can you please help me with that?

**Comment by dhirajpatra** [comment]
I think you have to install all NPM packages first.
